
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - vendor
disabled_rules:
  - block_based_kvo
  - discarded_notification_center_observer
  - trailing_whitespace
  - force_cast
  - todo
  - identifier_name

opt_in_rules:
  - attributes
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - joined_default_parameter
  - literal_expression_end_indentation
  - overridden_super_call
  - override_in_extension
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

#explicit set of warning level
line_length: 200
