# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Products' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Products
  pod 'SwiftLint'
  pod 'Bond'
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'NVActivityIndicatorView'

end
